
logging:
    file:
        name: cplace-admin.log

spring:
    cloud:
        discovery:
            client:
                simple:
                    instances:
                        test:
                            - uri: http://localhost:8083
                              metadata:
                                  management.context-path: /_actuator
                                  user.name: tricia
                                  user.password: topsecret


    boot:
        admin:
            ui:
                brand: <img src="assets/img/cplace-logo.png"><span>cplace admin</span>
                cache:
                    no-cache: true
                cache-templates: false
                extension-resource-locations: classpath:/META-INF/spring-boot-admin-server-ui/extensions/custom/
                favicon: assets/img/fav-icon.png
                login-icon: assets/img/cplace-logo.png
                title: cplace admin
                view-settings:
                    - name: "about"
                      enabled: false
    jmx:
        enabled: true
    security:
        user:
            name: tricia
            password: topsecret

